# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 04:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('feature_details', models.TextField()),
                ('published_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('tag', models.CharField(choices=[('Feature Request', 'Feature Request')], default='Feature Request', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=6)),
                ('development_status', models.CharField(choices=[('To Do', 'To Do'), ('Currently Being Investigated', 'Currently Being Investigated'), ('In Development', 'In Development'), ('In Testing', 'In Testing'), ('Issue Resolved', 'Issue Resolved')], default='To Do', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('users', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
